export interface FeatureDefinition {
  name: string;
  label: string;
  type: "number" | "categorical" | "boolean";
  unit?: string;
  description: string;
  required: boolean;
  min?: number;
  max?: number;
  options?: { value: string; label: string }[];
  defaultValue?: number | string | boolean;
}

export interface DiseaseMetadata {
  id: string;
  name: string;
  code: string;
  modelFileName: string;
  description: string;
  datasetName: string;
  features: FeatureDefinition[];
}

export const ALL_DISEASE_METADATA: DiseaseMetadata[] = [
  {
    id: "heart",
    name: "Heart Disease",
    code: "HEART",
    modelFileName: "heart_disease_model.joblib",
    description:
      "Cardiovascular risk screening based on resting vitals, cholesterol, ECG, and stress test factors.",
    datasetName: "Cleveland Heart Disease Dataset / UCI Machine Learning Repository",
    features: [
      {
        name: "Age",
        label: "Age",
        type: "number",
        unit: "years",
        min: 18,
        max: 120,
        required: true,
        description: "Patient age",
      },
      {
        name: "Sex",
        label: "Sex",
        type: "categorical",
        required: true,
        description: "Biological sex",
      },
      {
        name: "ChestPainType",
        label: "Chest Pain Type",
        type: "categorical",
        required: true,
        description: "Type of chest pain reported",
      },
      {
        name: "RestingBP",
        label: "Resting Blood Pressure",
        type: "number",
        unit: "mmHg",
        min: 50,
        max: 260,
        required: true,
        description: "Resting systolic pressure",
      },
      {
        name: "Cholesterol",
        label: "Serum Cholesterol",
        type: "number",
        unit: "mg/dL",
        min: 50,
        max: 600,
        required: true,
        description: "Serum cholesterol reading",
      },
      {
        name: "FastingBS",
        label: "Fasting Blood Sugar > 120 mg/dL",
        type: "boolean",
        required: true,
        description: "Elevated fasting blood sugar",
      },
      {
        name: "RestingECG",
        label: "Resting ECG Results",
        type: "categorical",
        required: true,
        description: "Resting electrocardiographic results",
      },
      {
        name: "MaxHR",
        label: "Maximum Heart Rate Achieved",
        type: "number",
        unit: "bpm",
        min: 60,
        max: 220,
        required: true,
        description: "Max heart rate",
      },
      {
        name: "ExerciseAngina",
        label: "Exercise-Induced Angina",
        type: "boolean",
        required: true,
        description: "Angina induced by exercise",
      },
      {
        name: "Oldpeak",
        label: "ST Depression (Oldpeak)",
        type: "number",
        min: 0,
        max: 10,
        required: true,
        description: "ST depression induced by exercise",
      },
      {
        name: "ST_Slope",
        label: "Slope of Peak Exercise ST Segment",
        type: "categorical",
        required: true,
        description: "Peak exercise ST segment slope",
      },
    ],
  },
  {
    id: "diabetes",
    name: "Diabetes",
    code: "DIABETES",
    modelFileName: "diabetes_model.joblib",
    description: "Diagnostic risk screening for metabolic dysfunction and Type-2 diabetes.",
    datasetName:
      "Pima Indians Diabetes Database / National Institute of Diabetes and Digestive and Kidney Diseases",
    features: [
      {
        name: "Pregnancies",
        label: "Pregnancies",
        type: "number",
        min: 0,
        max: 20,
        required: false,
        description: "Number of pregnancies",
      },
      {
        name: "Glucose",
        label: "Plasma Glucose Concentration",
        type: "number",
        unit: "mg/dL",
        min: 40,
        max: 500,
        required: true,
        description: "Plasma glucose concentration",
      },
      {
        name: "BloodPressure",
        label: "Diastolic Blood Pressure",
        type: "number",
        unit: "mmHg",
        min: 30,
        max: 180,
        required: true,
        description: "Diastolic blood pressure",
      },
      {
        name: "SkinThickness",
        label: "Triceps Skin Fold Thickness",
        type: "number",
        unit: "mm",
        min: 0,
        max: 99,
        required: false,
        description: "Skin fold thickness",
      },
      {
        name: "Insulin",
        label: "2-Hour Serum Insulin",
        type: "number",
        unit: "mu U/ml",
        min: 0,
        max: 900,
        required: false,
        description: "Serum insulin",
      },
      {
        name: "BMI",
        label: "Body Mass Index (BMI)",
        type: "number",
        unit: "kg/m²",
        min: 10,
        max: 70,
        required: true,
        description: "Body Mass Index",
      },
      {
        name: "DiabetesPedigreeFunction",
        label: "Diabetes Pedigree Function",
        type: "number",
        min: 0.05,
        max: 2.5,
        required: false,
        description: "Family genetic pedigree score",
      },
      {
        name: "Age",
        label: "Age",
        type: "number",
        unit: "years",
        min: 18,
        max: 120,
        required: true,
        description: "Patient age",
      },
    ],
  },
  {
    id: "breast_cancer",
    name: "Breast Cancer",
    code: "BREAST_CANCER",
    modelFileName: "breast_cancer_model.joblib",
    description:
      "Biopsy cell nucleus biometric morphology evaluation (Wisconsin Diagnostic Benchmark).",
    datasetName: "Wisconsin Diagnostic Breast Cancer (WDBC) / UCI Machine Learning",
    features: [
      {
        name: "radius_mean",
        label: "Mean Radius",
        type: "number",
        min: 5,
        max: 35,
        required: true,
        description: "Mean distances from center to perimeter",
      },
      {
        name: "texture_mean",
        label: "Mean Texture",
        type: "number",
        min: 5,
        max: 45,
        required: true,
        description: "Standard deviation of gray-scale values",
      },
      {
        name: "perimeter_mean",
        label: "Mean Perimeter",
        type: "number",
        min: 40,
        max: 200,
        required: true,
        description: "Perimeter size",
      },
      {
        name: "area_mean",
        label: "Mean Area",
        type: "number",
        min: 100,
        max: 2600,
        required: true,
        description: "Nucleus area",
      },
      {
        name: "smoothness_mean",
        label: "Mean Smoothness",
        type: "number",
        min: 0.05,
        max: 0.25,
        required: true,
        description: "Local variation in radius lengths",
      },
    ],
  },
  {
    id: "kidney",
    name: "Kidney Disease",
    code: "KIDNEY",
    modelFileName: "kidney_disease_model.joblib",
    description:
      "Chronic kidney disease (CKD) risk evaluation using renal chemistry and urinalysis markers.",
    datasetName: "Chronic Kidney Disease Dataset / Apollo Hospitals & UCI Repository",
    features: [
      {
        name: "age",
        label: "Age",
        type: "number",
        unit: "years",
        min: 1,
        max: 120,
        required: true,
        description: "Patient age",
      },
      {
        name: "bp",
        label: "Blood Pressure",
        type: "number",
        unit: "mmHg",
        min: 50,
        max: 200,
        required: true,
        description: "Blood pressure",
      },
      {
        name: "sg",
        label: "Specific Gravity",
        type: "number",
        min: 1.005,
        max: 1.03,
        required: false,
        description: "Urine specific gravity",
      },
      {
        name: "bgr",
        label: "Blood Glucose Random",
        type: "number",
        unit: "mg/dL",
        min: 50,
        max: 500,
        required: false,
        description: "Random glucose",
      },
      {
        name: "bu",
        label: "Blood Urea",
        type: "number",
        unit: "mg/dL",
        min: 5,
        max: 400,
        required: false,
        description: "Blood urea",
      },
      {
        name: "sc",
        label: "Serum Creatinine",
        type: "number",
        unit: "mg/dL",
        min: 0.2,
        max: 20,
        required: true,
        description: "Serum creatinine",
      },
      {
        name: "hemo",
        label: "Hemoglobin",
        type: "number",
        unit: "g/dL",
        min: 3,
        max: 20,
        required: true,
        description: "Hemoglobin level",
      },
    ],
  },
  {
    id: "liver",
    name: "Liver Disease",
    code: "LIVER",
    modelFileName: "liver_disease_model.joblib",
    description:
      "Hepatic functional impairment assessment utilizing liver enzymes and bilirubin panels.",
    datasetName: "Indian Liver Patient Records (ILPD) / UCI Machine Learning",
    features: [
      {
        name: "Age",
        label: "Age",
        type: "number",
        unit: "years",
        min: 4,
        max: 100,
        required: true,
        description: "Patient age",
      },
      {
        name: "Total_Bilirubin",
        label: "Total Bilirubin",
        type: "number",
        unit: "mg/dL",
        min: 0.1,
        max: 80,
        required: true,
        description: "Total bilirubin",
      },
      {
        name: "Direct_Bilirubin",
        label: "Direct Bilirubin",
        type: "number",
        unit: "mg/dL",
        min: 0.1,
        max: 25,
        required: false,
        description: "Direct bilirubin",
      },
      {
        name: "Alkaline_Phosphotase",
        label: "Alkaline Phosphatase",
        type: "number",
        unit: "IU/L",
        min: 50,
        max: 2500,
        required: false,
        description: "Alkaline phosphatase",
      },
      {
        name: "Alamine_Aminotransferase",
        label: "Alamine Aminotransferase (SGPT)",
        type: "number",
        unit: "IU/L",
        min: 5,
        max: 2000,
        required: true,
        description: "ALT enzyme level",
      },
      {
        name: "Aspartate_Aminotransferase",
        label: "Aspartate Aminotransferase (SGOT)",
        type: "number",
        unit: "IU/L",
        min: 5,
        max: 5000,
        required: false,
        description: "AST enzyme level",
      },
      {
        name: "Albumin",
        label: "Albumin",
        type: "number",
        unit: "g/dL",
        min: 0.5,
        max: 6,
        required: true,
        description: "Serum albumin",
      },
    ],
  },
  {
    id: "stroke",
    name: "Stroke",
    code: "STROKE",
    modelFileName: "stroke_model.joblib",
    description: "Cerebrovascular accident and acute ischemic stroke probability calculation.",
    datasetName: "Stroke Prediction Dataset / Kaggle Healthcare Data",
    features: [
      {
        name: "gender",
        label: "Gender",
        type: "categorical",
        required: true,
        description: "Biological sex",
      },
      {
        name: "age",
        label: "Age",
        type: "number",
        unit: "years",
        min: 1,
        max: 120,
        required: true,
        description: "Patient age",
      },
      {
        name: "hypertension",
        label: "Hypertension History",
        type: "boolean",
        required: true,
        description: "Diagnosed hypertension",
      },
      {
        name: "heart_disease",
        label: "Heart Disease History",
        type: "boolean",
        required: true,
        description: "Pre-existing heart disease",
      },
      {
        name: "avg_glucose_level",
        label: "Average Blood Glucose",
        type: "number",
        unit: "mg/dL",
        min: 40,
        max: 400,
        required: true,
        description: "Blood glucose level",
      },
      {
        name: "bmi",
        label: "BMI",
        type: "number",
        unit: "kg/m²",
        min: 10,
        max: 80,
        required: true,
        description: "Body Mass Index",
      },
    ],
  },
  {
    id: "parkinsons",
    name: "Parkinson's Disease",
    code: "PARKINSONS",
    modelFileName: "parkinsons_model.joblib",
    description:
      "Biomedical phonation and vocal frequency perturbation analysis for neurodegenerative detection.",
    datasetName: "Parkinson's Disease Telemonitoring / UCI Machine Learning",
    features: [
      {
        name: "MDVP:Fo(Hz)",
        label: "Average Vocal Fundamental Frequency",
        type: "number",
        unit: "Hz",
        min: 50,
        max: 300,
        required: true,
        description: "Mean pitch frequency",
      },
      {
        name: "MDVP:Jitter(%)",
        label: "Frequency Variation (Jitter)",
        type: "number",
        unit: "%",
        min: 0.001,
        max: 0.1,
        required: true,
        description: "Vocal jitter ratio",
      },
      {
        name: "MDVP:Shimmer",
        label: "Amplitude Variation (Shimmer)",
        type: "number",
        min: 0.005,
        max: 0.2,
        required: true,
        description: "Local shimmer",
      },
      {
        name: "HNR",
        label: "Harmonics-to-Noise Ratio",
        type: "number",
        unit: "dB",
        min: 5,
        max: 40,
        required: true,
        description: "HNR measurement",
      },
      {
        name: "RPDE",
        label: "Recurrence Period Density Entropy",
        type: "number",
        min: 0.1,
        max: 0.9,
        required: true,
        description: "Dynamical complexity",
      },
    ],
  },
  {
    id: "thyroid",
    name: "Thyroid Disease",
    code: "THYROID",
    modelFileName: "thyroid_model.joblib",
    description:
      "Endocrine screening for hypothyroidism and hyperthyroidism from serum hormone assays.",
    datasetName: "Garavan Thyroid Disease Database / UCI Machine Learning",
    features: [
      {
        name: "age",
        label: "Age",
        type: "number",
        unit: "years",
        min: 1,
        max: 120,
        required: true,
        description: "Patient age",
      },
      {
        name: "sex",
        label: "Sex",
        type: "categorical",
        required: true,
        description: "Biological sex",
      },
      {
        name: "TSH",
        label: "Thyroid Stimulating Hormone (TSH)",
        type: "number",
        unit: "mIU/L",
        min: 0.01,
        max: 100,
        required: true,
        description: "Serum TSH level",
      },
      {
        name: "T3",
        label: "Triiodothyronine (T3)",
        type: "number",
        unit: "nmol/L",
        min: 0.1,
        max: 15,
        required: false,
        description: "Serum T3 level",
      },
      {
        name: "TT4",
        label: "Total Thyroxine (TT4)",
        type: "number",
        unit: "nmol/L",
        min: 1,
        max: 300,
        required: false,
        description: "Serum TT4 level",
      },
    ],
  },
  {
    id: "lung_cancer",
    name: "Lung Cancer",
    code: "LUNG_CANCER",
    modelFileName: "lung_cancer_model.joblib",
    description: "Pulmonary symptom cluster and environmental/lifestyle risk stratification.",
    datasetName: "Survey Lung Cancer Dataset / Kaggle Health",
    features: [
      {
        name: "GENDER",
        label: "Biological Gender",
        type: "categorical",
        required: true,
        description: "Patient gender",
      },
      {
        name: "AGE",
        label: "Age",
        type: "number",
        unit: "years",
        min: 18,
        max: 100,
        required: true,
        description: "Patient age",
      },
      {
        name: "SMOKING",
        label: "Smoking Exposure",
        type: "boolean",
        required: true,
        description: "Tobacco usage",
      },
      {
        name: "YELLOW_FINGERS",
        label: "Yellow Fingers",
        type: "boolean",
        required: false,
        description: "Nicotine staining on fingers",
      },
      {
        name: "ANXIETY",
        label: "Anxiety",
        type: "boolean",
        required: false,
        description: "Reported anxiety",
      },
      {
        name: "CHRONIC_DISEASE",
        label: "Chronic Respiratory Disease",
        type: "boolean",
        required: false,
        description: "Pre-existing COPD or asthma",
      },
      {
        name: "FATIGUE",
        label: "Fatigue",
        type: "boolean",
        required: false,
        description: "Persistent fatigue",
      },
      {
        name: "WHEEZING",
        label: "Wheezing",
        type: "boolean",
        required: false,
        description: "Audible wheezing",
      },
      {
        name: "COUGHING",
        label: "Chronic Coughing",
        type: "boolean",
        required: true,
        description: "Persistent cough",
      },
      {
        name: "SHORTNESS_OF_BREATH",
        label: "Shortness of Breath",
        type: "boolean",
        required: true,
        description: "Dyspnea",
      },
    ],
  },
  {
    id: "alzheimers",
    name: "Alzheimer's Disease",
    code: "ALZHEIMERS",
    modelFileName: "alzheimers_model.joblib",
    description: "Cognitive assessment and neurodegenerative risk score.",
    datasetName:
      "Alzheimer's Disease Neuroimaging Initiative (ADNI) & Clinical Cognitive Inventory",
    features: [
      {
        name: "Age",
        label: "Age",
        type: "number",
        unit: "years",
        min: 55,
        max: 105,
        required: true,
        description: "Patient age",
      },
      {
        name: "MMSE",
        label: "Mini-Mental State Examination Score",
        type: "number",
        min: 0,
        max: 30,
        required: true,
        description: "Standard MMSE cognitive score",
      },
      {
        name: "FunctionalAssessment",
        label: "Functional Assessment Score",
        type: "number",
        min: 0,
        max: 10,
        required: true,
        description: "Daily living functional rating",
      },
      {
        name: "MemoryComplaints",
        label: "Reported Memory Complaints",
        type: "boolean",
        required: true,
        description: "Subjective or reported memory loss",
      },
      {
        name: "BehavioralProblems",
        label: "Behavioral Changes",
        type: "boolean",
        required: false,
        description: "Personality or behavioral changes",
      },
      {
        name: "ADL",
        label: "Activities of Daily Living Score",
        type: "number",
        min: 0,
        max: 10,
        required: false,
        description: "ADL capability score",
      },
    ],
  },
];
