import type { DiseaseMetadataClient } from "./types";

export const DISEASE_CONFIGS: DiseaseMetadataClient[] = [
  {
    id: "heart_disease",
    name: "Heart Disease",
    code: "HEART",
    endpoint: "/api/predict/heart_disease",
    modelFileName: "heart_disease_model.joblib",
    scalerFileName: "heart_disease_scaler.joblib",
    description:
      "Evaluates coronary artery and cardiovascular risk from blood pressure, serum cholesterol, fasting blood sugar, and clinical indicators.",
    dataset: "UCI Cleveland & Statlog Heart Disease Dataset",
    recommendedNextStep:
      "Schedule a cardiology consultation, 12-lead ECG, and complete fasting lipid profile.",
    requiredFeatureNames: ["Age", "Sex", "RestingBP", "Cholesterol"],
    features: [
      {
        name: "age",
        label: "Age",
        type: "number",
        unit: "years",
        required: true,
        category: "demographics",
      },
      {
        name: "sex",
        label: "Sex",
        type: "select",
        required: true,
        category: "demographics",
      },
      {
        name: "systolic_bp",
        label: "Resting Systolic BP",
        type: "number",
        unit: "mmHg",
        required: true,
        category: "vitals",
      },
      {
        name: "cholesterol",
        label: "Serum Cholesterol",
        type: "number",
        unit: "mg/dL",
        required: true,
        category: "labs",
      },
      {
        name: "heart_rate",
        label: "Heart Rate / Max HR",
        type: "number",
        unit: "bpm",
        required: false,
        category: "vitals",
      },
      {
        name: "glucose",
        label: "Fasting Blood Glucose",
        type: "number",
        unit: "mg/dL",
        required: false,
        category: "labs",
      },
    ],
  },
  {
    id: "diabetes",
    name: "Diabetes",
    code: "DIAB",
    endpoint: "/api/predict/diabetes",
    modelFileName: "diabetes_model.joblib",
    scalerFileName: "diabetes_scaler.joblib",
    description:
      "Assesses glycemic dysregulation and Type 2 diabetes likelihood using plasma glucose, BMI, blood pressure, and age.",
    dataset: "PIMA Indians Diabetes Database (NIDDK)",
    recommendedNextStep:
      "Confirm glycemic status with a fasting plasma glucose test and HbA1c panel.",
    requiredFeatureNames: ["Glucose", "BMI", "Age"],
    features: [
      {
        name: "glucose",
        label: "Plasma Glucose",
        type: "number",
        unit: "mg/dL",
        required: true,
        category: "labs",
      },
      {
        name: "bmi",
        label: "Body Mass Index (BMI)",
        type: "number",
        unit: "kg/m²",
        required: true,
        category: "vitals",
      },
      {
        name: "age",
        label: "Age",
        type: "number",
        unit: "years",
        required: true,
        category: "demographics",
      },
      {
        name: "diastolic_bp",
        label: "Diastolic Blood Pressure",
        type: "number",
        unit: "mmHg",
        required: false,
        category: "vitals",
      },
    ],
  },
  {
    id: "breast_cancer",
    name: "Breast Cancer",
    code: "BRCA",
    endpoint: "/api/predict/breast_cancer",
    modelFileName: "breast_cancer_model.joblib",
    scalerFileName: "breast_cancer_scaler.joblib",
    description:
      "Evaluates Fine Needle Aspirate (FNA) breast mass cell nuclei morphometry (radius, texture, perimeter, area).",
    dataset: "Wisconsin Diagnostic Breast Cancer (WDBC) Dataset",
    recommendedNextStep:
      "Consult an oncologist or breast specialist for diagnostic mammography/ultrasound and pathology review.",
    requiredFeatureNames: ["radius_mean", "texture_mean", "perimeter_mean", "area_mean"],
    features: [
      {
        name: "radius_mean",
        label: "Mean Cell Radius",
        type: "number",
        unit: "mm",
        required: true,
        category: "clinical",
      },
      {
        name: "texture_mean",
        label: "Mean Cell Texture",
        type: "number",
        required: true,
        category: "clinical",
      },
      {
        name: "perimeter_mean",
        label: "Mean Cell Perimeter",
        type: "number",
        unit: "mm",
        required: true,
        category: "clinical",
      },
      {
        name: "area_mean",
        label: "Mean Cell Area",
        type: "number",
        unit: "mm²",
        required: true,
        category: "clinical",
      },
    ],
  },
  {
    id: "kidney_disease",
    name: "Kidney Disease",
    code: "KIDNEY",
    endpoint: "/api/predict/kidney_disease",
    modelFileName: "kidney_disease_model.joblib",
    scalerFileName: "kidney_disease_scaler.joblib",
    description:
      "Evaluates chronic kidney disease (CKD) indicators from serum creatinine, blood urea, hemoglobin, and blood pressure.",
    dataset: "UCI Chronic Kidney Disease Clinical Dataset",
    recommendedNextStep:
      "Order a comprehensive metabolic panel (eGFR, serum creatinine, BUN) and urinalysis with a nephrologist.",
    requiredFeatureNames: ["age", "sc", "hemo"],
    features: [
      {
        name: "age",
        label: "Age",
        type: "number",
        unit: "years",
        required: true,
        category: "demographics",
      },
      {
        name: "creatinine",
        label: "Serum Creatinine (sc)",
        type: "number",
        unit: "mg/dL",
        required: true,
        category: "labs",
      },
      {
        name: "hemoglobin",
        label: "Hemoglobin (hemo)",
        type: "number",
        unit: "g/dL",
        required: true,
        category: "labs",
      },
      {
        name: "urea",
        label: "Blood Urea (bu)",
        type: "number",
        unit: "mg/dL",
        required: false,
        category: "labs",
      },
    ],
  },
  {
    id: "liver_disease",
    name: "Liver Disease",
    code: "LIVER",
    endpoint: "/api/predict/liver_disease",
    modelFileName: "liver_disease_model.joblib",
    scalerFileName: "liver_disease_scaler.joblib",
    description:
      "Evaluates hepatic function using bilirubin, alkaline phosphatase, transaminases (ALT/AST), and serum albumin.",
    dataset: "Indian Liver Patient Dataset (ILPD)",
    recommendedNextStep:
      "Perform a complete liver function panel (ALT, AST, ALP, Bilirubin, Albumin) and hepatobiliary ultrasound.",
    requiredFeatureNames: [
      "Age",
      "Total_Bilirubin",
      "Alkaline_Phosphotase",
      "Alamine_Aminotransferase",
    ],
    features: [
      {
        name: "age",
        label: "Age",
        type: "number",
        unit: "years",
        required: true,
        category: "demographics",
      },
      {
        name: "total_bilirubin",
        label: "Total Bilirubin",
        type: "number",
        unit: "mg/dL",
        required: true,
        category: "labs",
      },
      {
        name: "alkaline_phosphotase",
        label: "Alkaline Phosphatase (ALP)",
        type: "number",
        unit: "IU/L",
        required: true,
        category: "labs",
      },
      {
        name: "sgpt",
        label: "ALT / SGPT",
        type: "number",
        unit: "IU/L",
        required: true,
        category: "labs",
      },
      {
        name: "sgot",
        label: "AST / SGOT",
        type: "number",
        unit: "IU/L",
        required: false,
        category: "labs",
      },
      {
        name: "albumin",
        label: "Serum Albumin",
        type: "number",
        unit: "g/dL",
        required: false,
        category: "labs",
      },
    ],
  },
  {
    id: "stroke",
    name: "Stroke",
    code: "STROKE",
    endpoint: "/api/predict/stroke",
    modelFileName: "stroke_disease_model.joblib",
    scalerFileName: "stroke_scaler.joblib",
    description:
      "Evaluates cerebrovascular stroke risk from age, hypertension, heart disease history, average glucose level, and BMI.",
    dataset: "Healthcare Stroke Prediction Clinical Dataset",
    recommendedNextStep:
      "Review blood pressure control, carotid/cerebrovascular risk factors, and glycemic status with a physician.",
    requiredFeatureNames: ["age", "avg_glucose_level", "bmi"],
    features: [
      {
        name: "age",
        label: "Age",
        type: "number",
        unit: "years",
        required: true,
        category: "demographics",
      },
      {
        name: "glucose",
        label: "Average Glucose Level",
        type: "number",
        unit: "mg/dL",
        required: true,
        category: "labs",
      },
      {
        name: "bmi",
        label: "BMI",
        type: "number",
        unit: "kg/m²",
        required: true,
        category: "vitals",
      },
    ],
  },
  {
    id: "parkinsons",
    name: "Parkinson's Disease",
    code: "PARK",
    endpoint: "/api/predict/parkinsons",
    modelFileName: "parkinsons_model.joblib",
    scalerFileName: "parkinsons_scaler.joblib",
    description:
      "Evaluates biomedical voice phonation measures (fundamental frequency, jitter, shimmer, harmonics-to-noise ratio).",
    dataset: "Oxford Parkinson's Disease Telemonitoring Dataset",
    recommendedNextStep:
      "Consult a neurologist for motor and acoustic vocal assessment if tremor or phonatory changes are present.",
    requiredFeatureNames: ["MDVP_Fo_Hz", "MDVP_Jitter_Percent", "MDVP_Shimmer", "HNR"],
    features: [
      {
        name: "MDVP_Fo_Hz",
        label: "MDVP:Fo (Fundamental Freq)",
        type: "number",
        unit: "Hz",
        required: true,
        category: "clinical",
      },
      {
        name: "MDVP_Jitter_Percent",
        label: "MDVP:Jitter (%)",
        type: "number",
        unit: "%",
        required: true,
        category: "clinical",
      },
      {
        name: "MDVP_Shimmer",
        label: "MDVP:Shimmer",
        type: "number",
        unit: "dB",
        required: true,
        category: "clinical",
      },
      {
        name: "HNR",
        label: "Harmonics-to-Noise Ratio (HNR)",
        type: "number",
        unit: "dB",
        required: true,
        category: "clinical",
      },
    ],
  },
  {
    id: "thyroid",
    name: "Thyroid Disease",
    code: "THYR",
    endpoint: "/api/predict/thyroid",
    modelFileName: "thyroid_model.joblib",
    scalerFileName: "thyroid_scaler.joblib",
    description:
      "Evaluates endocrine thyroid function from Thyroid Stimulating Hormone (TSH), T3, and Total Thyroxine (TT4) levels.",
    dataset: "Garvan Institute / UCI Thyroid Disease Dataset",
    recommendedNextStep:
      "Review thyroid function panel (TSH, Free T3, Free T4) with an endocrinologist or primary care physician.",
    requiredFeatureNames: ["age", "TSH"],
    features: [
      {
        name: "age",
        label: "Age",
        type: "number",
        unit: "years",
        required: true,
        category: "demographics",
      },
      {
        name: "tsh",
        label: "TSH Level",
        type: "number",
        unit: "mIU/L",
        required: true,
        category: "labs",
      },
      {
        name: "t3",
        label: "T3 Resin / Free T3",
        type: "number",
        unit: "nmol/L",
        required: false,
        category: "labs",
      },
      {
        name: "tt4",
        label: "Total Thyroxine (TT4)",
        type: "number",
        unit: "nmol/L",
        required: false,
        category: "labs",
      },
    ],
  },
  {
    id: "lung_cancer",
    name: "Lung Cancer",
    code: "LUNG",
    endpoint: "/api/predict/lung_cancer",
    modelFileName: "lung_cancer_model.joblib",
    scalerFileName: "lung_cancer_scaler.joblib",
    description:
      "Evaluates pulmonary risk factors from age, sex, smoking history, and respiratory symptom profile.",
    dataset: "Clinical Pulmonary & Lung Cancer Survey Dataset",
    recommendedNextStep:
      "Discuss respiratory symptoms, smoking cessation, and low-dose chest CT screening with a pulmonologist.",
    requiredFeatureNames: ["AGE", "GENDER"],
    features: [
      {
        name: "age",
        label: "Age",
        type: "number",
        unit: "years",
        required: true,
        category: "demographics",
      },
      {
        name: "sex",
        label: "Sex",
        type: "select",
        required: true,
        category: "demographics",
      },
      {
        name: "smoking",
        label: "Smoking History",
        type: "select",
        required: false,
        category: "lifestyle",
      },
    ],
  },
  {
    id: "alzheimers",
    name: "Alzheimer's Disease",
    code: "ALZ",
    endpoint: "/api/predict/alzheimers",
    modelFileName: "alzheimers_model.joblib",
    scalerFileName: "alzheimers_scaler.joblib",
    description:
      "Evaluates neurodegenerative cognitive risk using MMSE score, Functional Assessment score, age, and cardiovascular factors.",
    dataset: "Clinical Alzheimer's & Cognitive Assessment Dataset",
    recommendedNextStep:
      "Schedule a formal cognitive and neurological assessment (MMSE / MoCA) with a neurologist or memory clinic.",
    requiredFeatureNames: ["Age", "MMSE", "FunctionalAssessment"],
    features: [
      {
        name: "age",
        label: "Age",
        type: "number",
        unit: "years",
        required: true,
        category: "demographics",
      },
      {
        name: "MMSE",
        label: "MMSE Cognitive Score (0-30)",
        type: "number",
        unit: "pts",
        required: true,
        category: "clinical",
      },
      {
        name: "FunctionalAssessment",
        label: "Functional Assessment Score (0-10)",
        type: "number",
        unit: "pts",
        required: true,
        category: "clinical",
      },
    ],
  },
];

export const SYMPTOM_OPTIONS = [
  "Fatigue",
  "Cough",
  "Shortness of breath",
  "Chest pain",
  "Wheezing",
  "Difficulty swallowing",
  "Frequent urination",
  "Excessive thirst",
  "Dizziness",
  "Headache",
  "Memory problems",
  "Tremor",
  "Joint pain",
  "Nausea",
] as const;

export const ADDITIONAL_SYMPTOM_OPTIONS = [
  "Palpitations",
  "Unexplained weight loss",
  "Weight gain",
  "Yellow fingers",
  "Anxiety",
  "Respiratory allergies",
  "Swelling in legs/ankles",
  "Jaundice (Yellow skin/eyes)",
  "Abdominal pain",
  "Dark urine",
  "Loss of appetite",
  "Vomiting",
  "Blurred vision",
  "Increased hunger",
  "Numbness or weakness",
  "Speech difficulty",
  "Confusion / Disorientation",
  "Muscle stiffness",
  "Balance / Gait difficulty",
  "Heat/Cold intolerance",
  "Hair loss",
  "Neck swelling",
  "Fever",
  "Night sweats",
  "Breast lump or tenderness",
  "Itchy skin",
] as const;

export const ALL_SYMPTOM_OPTIONS = [...SYMPTOM_OPTIONS, ...ADDITIONAL_SYMPTOM_OPTIONS] as const;
